// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbcmgvlmsxtmwmgqstbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiY21ndmxtc3h0bXdtZ3FzdGJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MTkyOTcsImV4cCI6MjA2ODI5NTI5N30.HKAXOTW7sXQ-KQXJx9ENCH6BkKKN46tSyDvxaRQ4EPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});